-- Restore the full-text search column dropped by 20260602144803_add_subject_color_icon.
--
-- That migration was generated by `prisma migrate dev` while the Page model did not
-- declare the column, so Prisma diffed it as drift and emitted a DROP. The model now
-- declares `searchVector Unsupported("tsvector")? @map("search_vector")`, which stops
-- the drop from being regenerated.

-- Add tsvector column for full-text search
ALTER TABLE "pages" ADD COLUMN "search_vector" tsvector
  GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))
  ) STORED;

-- GIN index for fast full-text queries
CREATE INDEX "pages_search_vector_idx" ON "pages" USING GIN ("search_vector");
